### ISSUE TITLE
Add ToUpper/ToLower for range of string

### ISSUE THREAD

**Issue by sdam-incom-it-dk** [Ithalica/dotNifties#2]
ToUpper and ToLower methods that take a start and end index to define what should be affected.

**Comment by Ithalica** [comment]
This has now been implemented. 
To new extensions (string.ToUpper and string.ToLower) have been added.
Both of these take startIndex and length. For a single character, length should just be one.

Maybe this should be an optional parameter that defaults to 1. 

Methods that look alike (substring, remove, etc.) apply to the rest of the string from the start index if nothing else is provided.
